# #######################################################################################
# AUTOSTART
# #######################################################################################

# ########################################
# System services
# ########################################

# Noctalia Shell (bar, dock, backgrounds, UI components)
exec-once = qs -c noctalia-shell --no-duplicate

# Authentication manager
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Hyprland plugin manager
# Reload plugins to avoid startup errors
# Used for split-monitor-workspaces plugin defined in hyprland.conf
exec-once = hyprpm reload -n

# Better systemd integration
# Import all environment variables from systemd to Wayland session
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
# Make systemd-aware apps work properly in Wayland
exec-once = dbus-update-activation-environment --systemd --all

# Hypridle (screen lock, suspend, idle detection)
exec-once = uwsm-app -- hypridle

# GPU Screenrecorder UI
exec-once = gsr-ui

# Audio Keepalive
# Script to prevent audio nodes from going to sleep
exec-once = audio-keepalive.sh

# Discord Pipewire Bridge
exec-once = nohup pipewire-bridge-fix run &

# ########################################
# Apps
# ########################################

# OpenRGB + Profile
exec-once = uwsm-app -- openrgb -p "main" --startminimized

# EasyEffects + Profile
exec-once = uwsm-app -- easyeffects --gapplication-service

# Clipse (clipboard manager)
exec-once = uwsm-app -- clipse -listen | clipse -enable-real-time | clipse -clear-all

# ########################################
# Preferences
# ########################################

# GTK app styling (adw-gtk3-dark = libadwaita dark theme)
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
# Prefer dark color scheme for GTK apps
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
