# #######################################################################################
# LOOK & FEEL
# #######################################################################################

# ########################################
# Windows & Workspaces
# ########################################

general {
  border_size = 3
  gaps_in = 6
  gaps_out = 11
  # Default tiling layout: dwindle (horizontal split)
  layout = dwindle
}

decoration {
 	rounding = 10
}

# Master layout (new windows become master)
# master {
#   new_status = master
# }

# Dwindle layout (horizontal split)
dwindle {
  force_split = 2
  pseudotile = true
  preserve_split = true
}

misc {
  force_default_wallpaper = 0
  disable_hyprland_logo = true
  focus_on_activate = true
}
