# #######################################################################################
# WINDOW RULES
# #######################################################################################

# ########################################
# General
# ########################################

# Completely deny apps being recorded. Used with clipboard manager clipse for privacy
windowrule {
  name = disallow-screenshare
  no_screen_share = on
  match:class = ^clipse(-gui)?$
}

# Suppress maximize events to fix flickering with some apps
windowrule {
  name = suppress-maximize-events
  match:class = .*
  suppress_event = maximize
}

# Fix issues with XWayland window drags
# Makes floating XWayland windows unfocusable to prevent drag issues
windowrule {
  name = fix-xwayland-drags
  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false
  no_focus = true
}

windowrule {
  name = floating-popups
  float = on
  center = on
  match:modal = true
}

windowrule {
  name = floating-popups-float
  float = on
  match:title = ^(Open File|Open Folder|Open|Save|Save As|Extract|Export|Import|Choose File|Rename|script-fu|kdenlive|brave|zen)$
  match:class = .*
}

windowrule {
  name = floating-popups-center
  center = on
  match:title = ^(Open File|Open Folder|Open|Save|Save As|Extract|Export|Import|Choose File|Rename|script-fu|kdenlive|brave|zen)$
  match:float = true
}

windowrule {
  name = floating-portals
  float = on
  center = on
  match:class = ^(xdg-desktop-portal-gtk|xdg-desktop-portal-hyprland|Xdg-desktop-portal-gtk|Xdg-desktop-portal-hyprland)$
}

windowrule {
  name = no-border-portal
  float = on
  center = on
  border_size = 0
  match:class = (Xdg-desktop-portal-gtk)
}

# Prevent idle timeout for apps tagged with "noidle" like video players
windowrule = idle_inhibit always, match:tag noidle

# ########################################
# Apps
# ########################################

# rules needed for noctalia screenshot plugins
layerrule = match:namespace noctalia-shell:regionSelector, no_anim on
layerrule = match:namespace noctalia-region-selector, no_anim on

windowrule {
  name = floating-terminal
  match:initial_class = ^(floating-terminal)$
  float = on
  stay_focused = on
  center = true
  size = 1200 800
}

windowrule {
  name = clipse-gui
  match:class = ^(clipse-gui)$
  float = on
  stay_focused = on
  move = 580 50
  size = 800 400
}

windowrule {
  name = resources
  match:class = ^(net.nokyan.Resources)$
  float = on
  size = 1400 700
}
