# #######################################################################################
# WINDOW RULES
# #######################################################################################

# ########################################
# General
# ########################################

# Default transparency for all windows
windowrule {
  name = transparency
  opacity = 0.89 0.89
  match:class = .*
}

# Disable transparency for apps that don't handle it well or which straightup just look ugly
windowrule {
  name = no-transparency
  opacity = 1.0
  match:class = ^(discord|zen|brave-browser-nightly|steam|zoom|vlc|mpv|org.kde.kdenlive|org.gnome.Decibels|org.gnome.Loupe|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer|com.gabm.satty)$
}

# Completely deny apps being recorded. Used with clipboard manager clipse for privacy
windowrule {
  name = disallow-screenshare
  no_screen_share = on
  match:class = ^clipse(-gui)?$
}

# Suppress maximize events to fix flickering with some apps
windowrule {
  name = suppress-maximize-events
  match:class = .*
  suppress_event = maximize
}

# Fix issues with XWayland window drags
# Makes floating XWayland windows unfocusable to prevent drag issues
windowrule {
  name = fix-xwayland-drags
  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false
  no_focus = true
}

windowrule {
  name = floating-popups
  float = on
  center = on
  match:modal = true
}

windowrule {
  name = floating-popups
  float = on
  center = on
  match:title = ^(Open File|Open Folder|Open|Save|Save As|Export|Import|Choose File|Rename|script-fu|kdenlive|brave|zen)$
  match:class = .*
}

windowrule {
  name = floating-portals
  float = on
  center = on
  match:class = ^(xdg-desktop-portal-gtk|xdg-desktop-portal-hyprland|Xdg-desktop-portal-gtk|Xdg-desktop-portal-hyprland)$
}

windowrule {
  name = no-border-portal
  float = on
  center = on
  border_size = 0
  match:class = (Xdg-desktop-portal-gtk)
}

# Prevent idle timeout for apps tagged with "noidle" like video players
windowrule = idle_inhibit always, match:tag noidle

# ########################################
# Apps
# ########################################

# screen-shot-and-record noctalia plugin
layerrule = match:namespace noctalia-shell:regionSelector, no_anim on
layerrule = match:namespace noctalia-region-selector, no_anim on

# Custom floating terminal rule
windowrule {
  name = floating-terminal
  match:initial_class = ^(floating-terminal)$
  float = on
  stay_focused = on
  center = true
  size = 1200 800
}

# Custom clipse clipboard manager rule
windowrule {
  name = clipse
  float = on
  size = 622 552
  stay_focused = on
  match:class = (clipse)
}

windowrule {
  name = terminal-transparency
  opacity = 0.85
  match:class = ^(kitty|alacritty)$
}

windowrule {
  name = editor-transparency
  opacity = 0.89
  match:class = (dev.zed.Zed)
}

windowrule {
  name = clipse-gui
  match:initial_class = ^(clipse-gui)$
  float = on
  stay_focused = on
  move = 580 50
  size = 800 400
}
