# #######################################################################################
# NOCTALIA COLORS
# #######################################################################################

$primary = rgb(332f49)
$surface = rgb(08080c)
$secondary = rgb(b87094)
$error = rgb(b87094)
$tertiary = rgb(8278b8)

$surface_lowest = rgb(0b0a0f)

general {
  col.active_border = $primary
  col.inactive_border = $surface
}

group {
  col.border_active = $secondary
  col.border_inactive = $surface
  col.border_locked_active = $error
  col.border_locked_inactive = $surface

  groupbar {
    col.active = $secondary
    col.inactive = $surface
    col.locked_active = $error
    col.locked_inactive = $surface
  }
}
