# #######################################################################################
# APPS
# #######################################################################################

source = ~/.config/hypr/apps/steam.conf
source = ~/.config/hypr/apps/cs2.conf
