# #######################################################################################
# COUNTER-STRIKE 2
# #######################################################################################

windowrule {
  name = force-instant-fullscreen
  fullscreen = on
  match:class = ^(cs2)$
}
